spring.application.name=FirstSpringProduct
server.port=1725
spring.datasource.url= jdbc:mysql://localhost:3306/sgic-db-demo?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username= root
spring.datasource.password= manager

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto= create
# Enable logging of DDL statements
spring.jpa.properties.hibernate.hbm2ddl.auto=update
# Enable logging of all SQL statements
spring.jpa.show-sql=true


combank.payment.gateway = "localhost:330/gateway?"

vat.percentage =



